
set_property IOSTANDARD LVCMOS33 [get_ports {out[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {out[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst]
set_property IOSTANDARD LVCMOS33 [get_ports stop]

set_property PACKAGE_PIN W5 [get_ports clk]
set_property PACKAGE_PIN W19 [get_ports rst]
set_property PACKAGE_PIN T18 [get_ports stop]

set_property PACKAGE_PIN P1 [get_ports {out[14]}]
set_property PACKAGE_PIN N3 [get_ports {out[13]}]
set_property PACKAGE_PIN P3 [get_ports {out[12]}]
set_property PACKAGE_PIN U3 [get_ports {out[11]}]
set_property PACKAGE_PIN W3 [get_ports {out[10]}]
set_property PACKAGE_PIN V3 [get_ports {out[9]}]
set_property PACKAGE_PIN V13 [get_ports {out[8]}]
set_property PACKAGE_PIN V14 [get_ports {out[7]}]
set_property PACKAGE_PIN U14 [get_ports {out[6]}]
set_property PACKAGE_PIN U15 [get_ports {out[5]}]
set_property PACKAGE_PIN W18 [get_ports {out[4]}]
set_property PACKAGE_PIN V19 [get_ports {out[3]}]
set_property PACKAGE_PIN U19 [get_ports {out[2]}]
set_property PACKAGE_PIN E19 [get_ports {out[1]}]
set_property PACKAGE_PIN U16 [get_ports {out[0]}]



set_property IOSTANDARD LVCMOS33 [get_ports {out[15]}]
set_property PACKAGE_PIN L1 [get_ports {out[15]}]

set_property IOSTANDARD LVCMOS33 [get_ports {D[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {D[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ssd[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports stop_state]
set_property PACKAGE_PIN L1 [get_ports stop_state]

set_property PACKAGE_PIN U2 [get_ports {ssd[0]}]
set_property PACKAGE_PIN U4 [get_ports {ssd[1]}]
set_property PACKAGE_PIN V4 [get_ports {ssd[2]}]
set_property PACKAGE_PIN W4 [get_ports {ssd[3]}]
set_property PACKAGE_PIN V8 [get_ports {D[4]}]
set_property PACKAGE_PIN U8 [get_ports {D[5]}]
set_property PACKAGE_PIN W6 [get_ports {D[6]}]
set_property PACKAGE_PIN W7 [get_ports {D[7]}]

set_property PACKAGE_PIN U5 [get_ports {D[3]}]
set_property PACKAGE_PIN V5 [get_ports {D[2]}]
set_property PACKAGE_PIN U7 [get_ports {D[1]}]
set_property PACKAGE_PIN V7 [get_ports {D[0]}]
